# ─────────────────────────────────────────────────────────────────────────────
# CodeGuard — DynamoDB table for conversation memory
# File: infra/dynamodb.tf
#
# Stores per-session conversation history so users can ask follow-up questions
# about a previous security review without re-submitting their code.
#
# Schema:
#   Partition key: session_id (String) — UUID generated by the backend
#   Attributes:    messages (List)     — list of {role, content} dicts
#                  ttl      (Number)   — Unix timestamp; item auto-deleted after 30 days
#
# Billing: PAY_PER_REQUEST (no capacity planning required for variable traffic).
# ─────────────────────────────────────────────────────────────────────────────

resource "aws_dynamodb_table" "memory" {
  name         = "${local.name}-memory"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "session_id"

  attribute {
    name = "session_id"
    type = "S"
  }

  # TTL — DynamoDB automatically deletes items when the current Unix timestamp
  # exceeds the value in the "ttl" attribute. Items older than 30 days are removed
  # without any manual maintenance. The deletion happens asynchronously within
  # 48 hours of the TTL expiry.
  ttl {
    attribute_name = "ttl"
    enabled        = true
  }

  tags = local.tags
}